
Oct 22, 2018

Development environment Sanskrit Lexicon Documentation

Revision of work originally done in 2014.


* setup of python3 on local computer
cd csldev
in git bash,

Oct 22, 2018

Sanskrit Lexicon Documentation system

Revision of work originally done in 2014.

* csldev
Development environment for Documentation
mkdir csldev

* python requirements for sphinx
sphinx version 1.8.1 requirements:Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
I have python 2.7 and Python3.7 on local windows 10 computer.
Cologne website has python3.4.

* Use python3 on local computer

* setup virtual environment with sphinx on local Windows 10 computer
assume using Git Bash terminal
1. retrieve zipped version of virtualenv
curl -O https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-16.0.0.tar.gz
2. unpack the compressed file:
tar xvfz virtualenv-16.0.0.tar.gz
# creates directory virtualenv-16.0.0
3. Make a directory to contain a new virtual environment:
# use python3
python3 virtualenv-16.0.0/virtualenv.py myenv
4. activate
# in csldev
source myenv/Scripts/activate
# checks
 which python
>>> /C/ejf/pdfs/TM2013/0docs/csldev/myenv/Scripts/python
# note that this is python version 3.7, presumably since i used 'python3'
# in creating the virtual environment.
 which pip
>>> /C/ejf/pdfs/TM2013/0docs/csldev/myenv/Scripts/pip
5. install sphinx
pip install sphinx
6. Deactivate virtual environment
deactivate
7. note on size:  myenv is 74MB
* quick commands for virtualenv
# in csldev directory
source myenv/Scripts/activate
deactivate

* initalizing test sphinx document
# besure myenv is activated
sphinx-quickstart

a) Separate source/build directories
 named 'source' and 'build'
* make copyright blank
in source/conf.py, change 
copyright = '2018, Jim Funderburk'
to 
copyright = ''
This copyright seems to show on all pages.
When blank, there is still a copyright to Sphinx and alabaster.
Guess we'll have to leave these.

* making html
sphinx-build -b html source build

The 'build' directory is constructed or updated.
We'll want to do some modification of this when uploading to 
Cologne.  Details later under 'Cologne upload'
* Cologne upload
* THE END
